version: '3.7'

services:
  backend:
    build: '.'
    container_name: crowdfunding_platform_api
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - minio
      - database
  minio:
    image: bitnami/minio:latest
    container_name: crowdfunding_platform_minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - '9900:9000'
      - '9901:9001'
  database:
    container_name: crowdfunding_platform_db
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres