server:
  port: 8080

minio:
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      resolve-lazily: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

tokens:
  access-secret-key: access-secret-key-access-secret-key-access-secret-key-access-secret-key
  refresh-secret-key: refresh-secret-key-refresh-secret-key-refresh-secret-key-refresh-secret-key
  access-lifetime-min: 30
  refresh-lifetime-days: 30

security:
  permit-all:
    endpoints:
      - pattern: /api/v1/auth/login
        method: POST
      - pattern: /api/v1/auth/register
        method: POST
      - pattern: /api/v1/auth/tokens
        method: POST
      - pattern: /api/v1/files/**
        method: POST
      - pattern: /api/v1/files/**
        method: GET